# Generated by Django 4.0.5 on 2022-06-25 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_alter_courses_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.courses')),
                ('users', models.ManyToManyField(related_name='enrollers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
