# Generated by Django 4.0.5 on 2022-06-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseenrolment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrolment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.courses'),
        ),
    ]
